//水管路径
var allPath = [
  [
    { rows: 0, cols: 0, style: 1 },
    { rows: 1, cols: 0, style: 1 },
    { rows: 2, cols: 0, style: 1 },
    { rows: 3, cols: 0, style: 2 },
    { rows: 3, cols: 1, style: 2 },
    { rows: 2, cols: 1, style: 2 },
    { rows: 2, cols: 2, style: 1 },
    { rows: 2, cols: 3, style: 1 },
    { rows: 2, cols: 4, style: 1 },
    { rows: 2, cols: 5, style: 1 },
    { rows: 2, cols: 6, style: 1 },
    { rows: 2, cols: 7, style: 2 },
    { rows: 3, cols: 7, style: 1 },
  ],

  [
    { rows: 0, cols: 0, style: 1 },
    { rows: 1, cols: 0, style: 1 },
    { rows: 2, cols: 0, style: 2 },
    { rows: 2, cols: 1, style: 2 },
    { rows: 1, cols: 1, style: 2 },
    { rows: 1, cols: 2, style: 2 },
    { rows: 2, cols: 2, style: 2 },
    { rows: 2, cols: 3, style: 1 },
    { rows: 2, cols: 4, style: 1 },
    { rows: 2, cols: 5, style: 1 },
    { rows: 2, cols: 6, style: 2 },
    { rows: 1, cols: 6, style: 2 },
    { rows: 1, cols: 7, style: 2 },
    { rows: 2, cols: 7, style: 1 },
    { rows: 3, cols: 7, style: 1 },
  ],

  [
    { rows: 0, cols: 0, style: 1 },
    { rows: 1, cols: 0, style: 1 },
    { rows: 2, cols: 0, style: 1 },
    { rows: 3, cols: 0, style: 2 },
    { rows: 3, cols: 1, style: 2 },
    { rows: 2, cols: 1, style: 1 },
    { rows: 1, cols: 1, style: 2 },
    { rows: 1, cols: 2, style: 1 },
    { rows: 1, cols: 3, style: 1 },
    { rows: 1, cols: 4, style: 1 },
    { rows: 1, cols: 5, style: 2 },
    { rows: 1, cols: 5, style: 2 },
    { rows: 2, cols: 5, style: 2 },
    { rows: 2, cols: 6, style: 1 },
    { rows: 2, cols: 7, style: 2 },
    { rows: 3, cols: 7, style: 1 },
  ],

  [
    { rows: 0, cols: 0, style: 1 },
    { rows: 1, cols: 0, style: 1 },
    { rows: 2, cols: 0, style: 1 },
    { rows: 3, cols: 0, style: 2 },
    { rows: 3, cols: 1, style: 2 },
    { rows: 2, cols: 1, style: 1 },
    { rows: 1, cols: 1, style: 1 },
    { rows: 0, cols: 1, style: 2 },
    { rows: 0, cols: 2, style: 2 },
    { rows: 1, cols: 2, style: 1 },
    { rows: 2, cols: 2, style: 2 },
    { rows: 2, cols: 3, style: 1 },
    { rows: 2, cols: 4, style: 1 },
    { rows: 2, cols: 5, style: 2 },
    { rows: 1, cols: 5, style: 1 },
    { rows: 0, cols: 5, style: 2 },
    { rows: 0, cols: 6, style: 1 },
    { rows: 0, cols: 6, style: 1 },
    { rows: 0, cols: 7, style: 2 },
    { rows: 1, cols: 7, style: 2 },
    { rows: 1, cols: 6, style: 2 },
    { rows: 2, cols: 6, style: 2 },
    { rows: 2, cols: 7, style: 2 },
    { rows: 3, cols: 7, style: 1 },
  ],
];